version: "3.4"

services:
  node:
    build:
      context: "node/"
    image: node-app
    ports:
      - 3001:3000


  vue_application:
    build:
      context: "vue_application/"
    image: vue_application
    env_file:
      - "./vue_application/.env"
    ports:
      - 5001:3000
