version: "3.4"

services:
  node:
    build:
      context: "node/"
    image: node-app
    ports:
      - 3001:3000


  vue:
    build:
      context: "vue/"
    image: vue-app
    env_file:
      - "./vue/.env"
    ports:
      - 5001:3000
